'use client';

import React from 'react';
import styles from '../settings.module.css';

export default function CodeViewerPage() {
    return (
        <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
            <header className={styles.pageHeader}>
                <h1>Codebase Explorer</h1>
            </header>
            <div className={styles.pageContent} style={{ padding: 0, display: 'flex', flex: 1 }}>
                {/* Mock File Tree */}
                <div style={{ width: '250px', borderRight: '1px solid #333', background: '#252526', display: 'flex', flexDirection: 'column' }}>
                    <div style={{ padding: '0.5rem 1rem', fontSize: '11px', color: '#999', letterSpacing: '1px' }}>EXPLORER</div>
                    <div style={{ padding: '0.25rem 1rem', fontSize: '13px', cursor: 'pointer', display: 'flex', gap: '8px' }}>
                        <span>📁</span> src
                    </div>
                    <div style={{ padding: '0.25rem 1rem', paddingLeft: '2rem', fontSize: '13px', cursor: 'pointer', color: 'var(--color-accent-blue)', background: '#37373d', display: 'flex', gap: '8px' }}>
                        <span>📄</span> page.tsx
                    </div>
                    <div style={{ padding: '0.25rem 1rem', paddingLeft: '2rem', fontSize: '13px', cursor: 'pointer', display: 'flex', gap: '8px' }}>
                        <span>📄</span> layout.tsx
                    </div>
                    <div style={{ padding: '0.25rem 1rem', paddingLeft: '2rem', fontSize: '13px', cursor: 'pointer', display: 'flex', gap: '8px' }}>
                        <span>📄</span> globals.css
                    </div>
                </div>

                {/* Mock Editor Area */}
                <div style={{ flex: 1, backgroundColor: '#1e1e1e', position: 'relative' }}>
                    <div style={{ display: 'flex', background: '#2d2d2d', borderBottom: '1px solid #111' }}>
                        <div style={{ padding: '8px 16px', background: '#1e1e1e', color: '#fff', fontSize: '12px', borderTop: '2px solid var(--color-accent-blue)' }}>
                            page.tsx
                        </div>
                    </div>
                    <pre style={{ padding: '1rem', margin: 0, color: '#d4d4d4', fontFamily: 'Consolas, "Courier New", monospace', fontSize: '13px', lineHeight: '1.5', overflowY: 'auto', height: 'calc(100% - 35px)' }}>
                        <code style={{ color: '#569cd6' }}>export default function</code> <code style={{ color: '#dcdcaa' }}>Home</code>() {'{\n'}
                        {'  '}return (\n
                        {'    '}<div>\n
                            {'      '}<h1>Welcome to Evolvable!</h1>\n
                            {'      '}<p>Select a project from the sidebar to begin.</p>\n
                            {'    '}</div>\n
                        {'  '});\n
                        {'}'}
                    </pre>

                    {/* Pending Phase 7 Integration Badge */}
                    <div style={{ position: 'absolute', bottom: '2rem', right: '2rem', background: 'rgba(0,0,0,0.8)', padding: '1rem', borderRadius: '8px', border: '1px solid #333', maxWidth: '300px' }}>
                        <div style={{ display: 'flex', alignItems: 'center', gap: '8px', marginBottom: '8px' }}>
                            <span style={{ fontSize: '18px' }}>✨</span>
                            <span style={{ color: '#fff', fontSize: '14px', fontWeight: 500 }}>Coming in Phase 7</span>
                        </div>
                        <p style={{ fontSize: '12px', color: '#aaa', margin: 0 }}>This is a placeholder for the integrated Monaco Editor. Once Phase 7 is complete, you will be able to edit the AST and Next.js React code generated by the AI natively here.</p>
                    </div>
                </div>
            </div>
        </div>
    );
}
