import { adminDb } from '../firebase/admin';
import { AuditEventType, AuditLogEntry } from '../agents/types';

/**
 * AuditLogger — append-only tamper-resistant audit trail.
 * Documents are written with add() (immutable IDs) and never updated.
 */
export class AuditLogger {
    private projectId: string;

    constructor(projectId: string) {
        this.projectId = projectId;
    }

    async log(
        event: AuditEventType,
        description: string,
        opts: {
            userId?: string;
            planVersion?: number;
            agentId?: string;
            metadata?: Record<string, any>;
        } = {}
    ): Promise<void> {
        try {
            const entry: Omit<AuditLogEntry, 'id'> = {
                event,
                timestamp: Date.now(),
                projectId: this.projectId,
                description,
                ...opts
            };

            // Firestore .add() generates an immutable document ID — append-only
            await adminDb.collection('auditLog').add(entry);

            // Also append to project-level log for quick retrieval
            await adminDb.collection('projects').doc(this.projectId).update({
                auditEvents: adminDb.collection('auditLog').doc().id // placeholder ref marker
            }).catch(() => { }); // non-fatal

            console.log(`[AuditLogger] ${event}: ${description}`);
        } catch (err) {
            // Never throw from audit logger — logging failure must not block pipeline
            console.error('[AuditLogger] Failed to write audit entry:', err);
        }
    }

    /** Convenience wrappers */
    planGenerated(planVersion: number, agentIds: string[]) {
        return this.log('plan_generated', `Implementation plan v${planVersion} generated by agents`, { planVersion, metadata: { agentIds } });
    }

    planRevisionRequested(fromVersion: number, notes: string, userId?: string) {
        return this.log('plan_revision_requested', `Revision requested from plan v${fromVersion}: ${notes}`, { userId, planVersion: fromVersion, metadata: { notes } });
    }

    planApproved(planVersion: number, userId: string) {
        return this.log('plan_approved', `Plan v${planVersion} explicitly approved by user`, { userId, planVersion });
    }

    planCancelled(planVersion: number, userId?: string) {
        return this.log('plan_cancelled', `Plan v${planVersion} cancelled`, { userId, planVersion });
    }

    executionStarted(planVersion: number) {
        return this.log('execution_started', `Execution pipeline started under approved plan v${planVersion}`, { planVersion });
    }

    planDrift(agentId: string, description: string) {
        return this.log('plan_drift', `Plan drift detected by ${agentId}: ${description}`, { agentId });
    }

    securityVeto(findings: number) {
        return this.log('security_veto', `Security agent vetoed deployment — ${findings} critical findings`);
    }

    qaGateFailed(coverage: number) {
        return this.log('qa_gate_failed', `QA gate failed — test coverage ${coverage}%`);
    }

    deployed(liveUrl: string) {
        return this.log('deployed', `Project deployed successfully to ${liveUrl}`);
    }

    // ── GitHub wrappers ──────────────────────────────────────────────────
    githubAccountLinked(userId: string, githubLogin: string) {
        return this.log('github_account_linked', `GitHub account @${githubLogin} connected`, { userId });
    }

    githubAccountUnlinked(userId: string, githubLogin: string) {
        return this.log('github_account_unlinked', `GitHub account @${githubLogin} disconnected`, { userId });
    }

    githubRepoCreated(repoFullName: string, planVersion: number) {
        return this.log('github_repo_created', `Repository '${repoFullName}' created`, { planVersion, metadata: { repoFullName } });
    }

    githubBranchCreated(branchName: string, planVersion: number) {
        return this.log('github_branch_created', `Branch '${branchName}' created`, { planVersion, metadata: { branchName } });
    }

    githubCommitted(commitSha: string, branchName: string, planVersion: number) {
        return this.log('github_committed', `Code committed to '${branchName}' — ${commitSha}`, { planVersion, metadata: { commitSha, branchName } });
    }

    githubPrOpened(prNumber: number, prUrl: string, planVersion: number) {
        return this.log('github_pr_opened', `Pull request #${prNumber} opened for review`, { planVersion, metadata: { prNumber, prUrl } });
    }

    prMerged(prNumber: number, commitSha: string) {
        return this.log('pr_merged', `PR #${prNumber} merged — deployment unlocked`, { metadata: { prNumber, commitSha } });
    }

    rollbackInitiated(version: number, commitSha: string) {
        return this.log('rollback_initiated', `Rollback to version ${version} initiated`, { planVersion: version, metadata: { commitSha } });
    }
}
