'use client';

import React from 'react';
import styles from '@/app/(workspace)/workspace.module.css';

export default function DatabasesPage() {
    return (
        <div style={{ display: 'flex', flexDirection: 'column', height: '100%' }}>
            <header className={styles.pageHeader}>
                <h1>Database Architecture</h1>
            </header>
            <div className={styles.pageContent}>
                <div style={{ maxWidth: '800px' }}>
                    <p style={{ fontSize: '14px', marginBottom: '2rem' }}>
                        View the relational schemas generated by the DB Architect. In Phase 7, you will be able to visually drag-and-drop relationships to map to the Component Builder.
                    </p>

                    <div style={{ background: '#252526', borderRadius: '4px', border: '1px solid #333', overflow: 'hidden' }}>
                        <div style={{ display: 'flex', borderBottom: '1px solid #333' }}>
                            <div style={{ padding: '0.75rem 1rem', borderRight: '1px solid #333', fontSize: '13px', fontWeight: 500, color: '#fff', background: '#2d2d2d' }}>users</div>
                            <div style={{ padding: '0.75rem 1rem', borderRight: '1px solid #333', fontSize: '13px', color: '#999', cursor: 'pointer' }}>products</div>
                            <div style={{ padding: '0.75rem 1rem', fontSize: '13px', color: '#999', cursor: 'pointer' }}>orders</div>
                        </div>
                        <div style={{ padding: '1.5rem' }}>
                            <table style={{ width: '100%', borderCollapse: 'collapse', fontSize: '13px' }}>
                                <thead>
                                    <tr style={{ color: '#999', textAlign: 'left' }}>
                                        <th style={{ paddingBottom: '0.5rem', borderBottom: '1px solid #333' }}>Column Name</th>
                                        <th style={{ paddingBottom: '0.5rem', borderBottom: '1px solid #333' }}>Type</th>
                                        <th style={{ paddingBottom: '0.5rem', borderBottom: '1px solid #333' }}>Constraints</th>
                                    </tr>
                                </thead>
                                <tbody>
                                    <tr>
                                        <td style={{ padding: '0.75rem 0', color: '#569cd6' }}>id</td>
                                        <td style={{ padding: '0.75rem 0', color: '#4ec9b0' }}>String / UUID</td>
                                        <td style={{ padding: '0.75rem 0', color: '#ce9178' }}>PRIMARY KEY</td>
                                    </tr>
                                    <tr>
                                        <td style={{ padding: '0.75rem 0', color: '#569cd6', borderTop: '1px solid #333' }}>email</td>
                                        <td style={{ padding: '0.75rem 0', color: '#4ec9b0', borderTop: '1px solid #333' }}>String</td>
                                        <td style={{ padding: '0.75rem 0', color: '#ce9178', borderTop: '1px solid #333' }}>UNIQUE, NOT NULL</td>
                                    </tr>
                                    <tr>
                                        <td style={{ padding: '0.75rem 0', color: '#569cd6', borderTop: '1px solid #333' }}>createdAt</td>
                                        <td style={{ padding: '0.75rem 0', color: '#4ec9b0', borderTop: '1px solid #333' }}>Timestamp</td>
                                        <td style={{ padding: '0.75rem 0', color: '#ce9178', borderTop: '1px solid #333' }}>DEFAULT CURRENT_TIMESTAMP</td>
                                    </tr>
                                </tbody>
                            </table>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    );
}
