import { GeneratedCodebase } from '../agents/types';

/**
 * Utility class to generate standardized Dockerfiles and .dockerignore files
 * for Next.js applications generated by the CodeGenerationAgent.
 */
export class DockerGenerator {

    /**
     * Generates a multi-stage Dockerfile optimized for Next.js 16 App Router
     * outputting a standalone server.
     */
    static generateDockerfile(): string {
        return `FROM node:20-alpine AS base

# Install dependencies only when needed
FROM base AS deps
# Check https://github.com/nodejs/docker-node/tree/b4117f9333da4138b03a546ec926ef50a31506c3#nodealpine to understand why libc6-compat might be needed.
RUN apk add --no-cache libc6-compat
WORKDIR /app

# Install dependencies based on the preferred package manager
COPY package.json package-lock.json* ./
RUN npm ci

# Rebuild the source code only when needed
FROM base AS builder
WORKDIR /app
COPY --from=deps /app/node_modules ./node_modules
COPY . .

# Next.js collects completely anonymous telemetry data about general usage.
# Learn more here: https://nextjs.org/telemetry
ENV NEXT_TELEMETRY_DISABLED 1

# If using Next.js 16 standalone output
RUN npm run build

# Production image, copy all the files and run next
FROM base AS runner
WORKDIR /app

ENV NODE_ENV production
ENV NEXT_TELEMETRY_DISABLED 1

RUN addgroup --system --gid 1001 nodejs
RUN adduser --system --uid 1001 nextjs

COPY --from=builder /app/public ./public

# Set the correct permission for prerender cache
RUN mkdir .next
RUN chown nextjs:nodejs .next

# Automatically leverage output traces to reduce image size
# https://nextjs.org/docs/advanced-features/output-file-tracing
COPY --from=builder --chown=nextjs:nodejs /app/.next/standalone ./
COPY --from=builder --chown=nextjs:nodejs /app/.next/static ./.next/static

USER nextjs

EXPOSE 3000
ENV PORT 3000

# server.js is created by next build from the standalone output
# https://nextjs.org/docs/pages/api-reference/next-config-js/output
CMD HOSTNAME="0.0.0.0" node server.js
`;
    }

    /**
     * Generates a standard .dockerignore file preventing local modules and build files
     * from polluting the container build context.
     */
    static generateDockerIgnore(): string {
        return `Dockerfile
.dockerignore
node_modules
npm-debug.log
README.md
.next
.git
.env.local
`;
    }

    /**
     * Injects the Docker configuration directly into the Codebase manifest.
     */
    static injectDockerConfig(codebase: GeneratedCodebase): GeneratedCodebase {
        return {
            ...codebase,
            files: {
                ...codebase.files,
                'Dockerfile': this.generateDockerfile(),
                '.dockerignore': this.generateDockerIgnore()
            }
        };
    }
}
